// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const FALLBACK_SUPABASE_URL = "https://missing-supabase-url.supabase.co";
const FALLBACK_SUPABASE_KEY = "missing-supabase-publishable-key";

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
export const supabaseUrl = SUPABASE_URL || FALLBACK_SUPABASE_URL;
export const supabasePublishableKey = SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_KEY;

const safeAuthStorage: Storage | undefined = (() => {
  if (typeof window === "undefined") return undefined;
  try {
    const key = "vibey-storage-check";
    window.localStorage.setItem(key, key);
    window.localStorage.removeItem(key);
    return window.localStorage;
  } catch {
    console.warn("localStorage is unavailable; Supabase auth will use in-memory session state.");
    return undefined;
  }
})();

const memoryAuthStorage = (() => {
  const store = new Map<string, string>();
  return {
    getItem: (key: string) => store.get(key) ?? null,
    setItem: (key: string, value: string) => {
      store.set(key, value);
    },
    removeItem: (key: string) => {
      store.delete(key);
    },
  };
})();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
  auth: {
    storage: safeAuthStorage ?? memoryAuthStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});